name: CI
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: jmgilman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix develop -c just check
